spring.application.name=backend
security.jwt.secret=my-super-secret-key-that-is-long-enough-to-be-secure
security.jwt.expiration-minutes=60
jwt.secret=M2M0YzhjMDVjZWFhNDEyNjgzMGU3YmVkZGZjZjQ5NDI1YTA0YzQwOTg5YzlmZjEyN2NkYzNlZmY0YTA2MWQ3ZQ==
server.port=${PORT:8080}
