spring:
  application:
    name: Manage360
  profiles:
    active: dev
server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:5174,http://localhost:5173,http://localhost:3000

#security:
#  jwt:
#    secret: your-secret-key
#    expiration-minutes: 60
